name: Dependency Security Scan

on:
  push:
    paths:
      - 'app/requirements.txt'
  pull_request:
    paths:
      - 'app/requirements.txt'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:
      inputs:
        name:
          description: "test"
          default: "test"
 

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install safety and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety
          pip install -r app/requirements.txt

      - name: Run safety check
        run: safety check -r app/requirements.txt

      - name: Install and run pip-audit
        run: |
          pip install pip-audit
          pip-audit -r app/requirements.txt

      - name: Check for duplicate dependencies
        run: |
          pip install reqs-check
          reqs-check check --duplicates app/requirements.txt